stages:
  - build

include:
  - project: "teleport/ci-cd/ci-scripts"
    ref: master
    file: "before-script.yml"

backend_build:
  stage: build
  rules:
  - if: $CI_COMMIT_TAG != null
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - docker login crtpdev.azurecr.io -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t "crtpdev.azurecr.io/tsa/education/2024/contacts-backend" -f ./Dockerfile .
    - docker push "crtpdev.azurecr.io/tsa/education/2024/contacts-backend"
    - docker rmi crtpdev.azurecr.io/tsa/education/2024/contacts-backend

frontend_build:
  stage: build
  rules:
  - if: $CI_COMMIT_TAG != null
  - if: $CI_PIPELINE_SOURCE == "web"
  - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - docker login crtpdev.azurecr.io -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t "crtpdev.azurecr.io/tsa/education/2024/contacts-frontend" -f ./frontend/Dockerfile .
    - docker push "crtpdev.azurecr.io/tsa/education/2024/contacts-frontend"
    - docker rmi crtpdev.azurecr.io/tsa/education/2024/contacts-frontend

