variables:
  IMAGE_NAME: crtpdev.azurecr.io/tsa/education/2024/contacts-
  IMAGE_NAME_BACKEND: backend
  IMAGE_NAME_FRONTEND: frontend

.default_build_scripts_backend: &default_build_scripts_backend
  - docker build -t ${IMAGE_NAME}${IMAGE_NAME_BACKEND}:${TAG} -f ./Dockerfile .
  - docker push ${IMAGE_NAME}${IMAGE_NAME_BACKEND}:${TAG}
  - docker rmi ${IMAGE_NAME}${IMAGE_NAME_BACKEND}:${TAG}

.default_build_scripts_frontend: &default_build_scripts_frontend
  - docker build -t ${IMAGE_NAME}${IMAGE_NAME_FRONTEND}:${TAG} -f ./frontend/Dockerfile ./frontend
  - docker push ${IMAGE_NAME}${IMAGE_NAME_FRONTEND}:${TAG}
  - docker rmi ${IMAGE_NAME}${IMAGE_NAME_FRONTEND}:${TAG}

.docker_login: &docker_login
  - docker login crtpdev.azurecr.io -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

include:
  - project: 'teleport/ci-cd/ci-scripts'
    ref: master
    file: 'before-script.yml'

backend_build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - *docker_login
    - *default_build_scripts_backend

frontend_build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - *docker_login
    - *default_build_scripts_frontend

deploy_stage:
  stage: deploy
  rules:
    # TODO delete this
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == "web"
    # TODO delete this
    - if: $CI_COMMIT_BRANCH == "dev"
      when: manual
    - if: $CI_COMMIT_BRANCH == "dev"
      when: on_success
      variables:
        TAG: 'stage-latest'
  script:
    - *docker_login
    - *default_build_scripts_backend
    - *default_build_scripts_frontend

    - mkdir -p ~/.ssh
    - eval "$(ssh-agent -s)"
    - echo "$SSH_IDENTITY_FILE" | tr -d '\r' | ssh-add -

    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - >
      ssh $SSH_USER@$SSH_HOST "bash -s" -- < ./deploy/deploy-stage.sh
      "CI_REGISTRY_USER='$CI_REGISTRY_USER'"
      "CI_REGISTRY_PASSWORD='$CI_REGISTRY_PASSWORD'"
      "DOCKER_REGISTRY_URL='$DOCKER_REGISTRY_URL'"
      "DOCKER_REGISTRY_AUTH='$DOCKER_REGISTRY_AUTH'"
