stages:
  - triggers

build:
  stage: triggers
  trigger:
    include: './gitlab-ci-triggers/.gitlab-ci.build.yml'
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "dev"

stage:
  stage: triggers
  trigger:
    include: './gitlab-ci-triggers/.gitlab-ci.stage.yml'
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"

helm:
  stage: triggers
  trigger:
    include: './gitlab-ci-triggers/.gitlab-ci.helm.yml'
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"