version: '3'

networks:
  tsa_oa:

services:
  database:
    container_name: 'database-container'
    image: crtpdev.azurecr.io/mariadb:10.11.6-debian-11-r6
    # image: mariadb:lts
    restart: always
    env_file:
      - path: .env.production
        required: true
    expose:
      - 3306
    ports:
      - '3307:3306'
    healthcheck:
      interval: 30s
      retries: 3
      test: ['CMD', 'healthcheck.sh', '--su-mysql', '--connect', '--innodb_initialized']
      timeout: 30s
    networks:
      - tsa_oa
    volumes:
      - ./docker_volume/database:/var/lib/mysql:rw

  backend:
    container_name: 'backend-container'
    restart: always
    env_file:
      - path: .env.production
        required: true
    build:
      dockerfile: Dockerfile
      context: '.'
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - /node_modules
      - ./docker_volume/backend:/backend
    ports:
      - '4000:4000'
    networks:
      - tsa_oa

  frontend:
    container_name: 'frontend-container'
    restart: always
    env_file:
      - path: frontend/.env.production
        required: true
    build:
      dockerfile: Dockerfile
      context: './frontend'
    depends_on:
      - backend
    volumes:
      - /frontend/node_modules
      - ./docker_volume/frontend:/usr/src/app
    ports:
      - '80:80'
    networks:
      - tsa_oa
