apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
{{ include "common.labels.standard" . | indent 4 }}
{{ include "webapp-contacts-charts.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
{{ include "webapp-contacts-charts.selectorLabelsBackend" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "webapp-contacts-charts.selectorLabelsBackend" . | indent 8 }}
    spec:
      imagePullSecrets:
      - name: "{{ .Release.Name }}-{{ .Values.imageCredentials.name }}"
      serviceAccountName: {{ template "webapp-contacts-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
          - name: backend-port
            containerPort: {{ .Values.backend.service.port }}
            protocol: TCP
          env:
          - name: NODE_ENV
            value: {{ .Values.backend.env.NODE_ENV }}
          - name: HOST
            value: {{ .Values.backend.env.HOST }}
          - name: PORT
            value: {{ .Values.backend.env.PORT | quote }}
          - name: DB_HOST
            value: {{ .Values.backend.env.DB_HOST }}
          - name: DB_PORT
            value: {{ .Values.backend.env.DB_PORT | quote }}
          - name: MARIADB_USER
            value: {{ .Values.backend.env.MARIADB_USER }}
          - name: MARIADB_PASSWORD
            value: {{ .Values.backend.env.MARIADB_PASSWORD }}
          - name: MARIADB_DATABASE
            value: {{ .Values.backend.env.MARIADB_DATABASE }}
          - name: MARIADB_ROOT_PASSWORD
            value: {{ .Values.backend.env.MARIADB_ROOT_PASSWORD }}
          startupProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
            tcpSocket:
              port: {{ .Values.backend.service.port }}
          livenessProbe:
            periodSeconds: 5
            failureThreshold: 2
            tcpSocket:
              port: {{ .Values.backend.service.port }}
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.backend.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
