database:
  image:
    repository: crtpdev.azurecr.io/mariadb:10.11.6-debian-11-r6
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3306
  env:
    NODE_ENV: production
    HOST: "0.0.0.0"
    PORT: "4000"
    DB_HOST: database
    DB_PORT: "3306"
    MARIADB_USER: root
    MARIADB_PASSWORD: root
    MARIADB_DATABASE: contactsdatabase
    MARIADB_ROOT_PASSWORD: root

backend:
  image:
    repository: crtpdev.azurecr.io/tsa/education/2024/contacts-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4000
  env:
    NODE_ENV: production
    HOST: "0.0.0.0"
    PORT: "4000"
    DB_HOST: database
    DB_PORT: "3306"
    MARIADB_USER: $MARIADB_USER
    MARIADB_PASSWORD: $MARIADB_PASSWORD
    MARIADB_DATABASE: $MARIADB_DATABASE
    MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD

frontend:
  image:
    repository: crtpdev.azurecr.io/tsa/education/2024/contacts-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 8080
  env:
    NODE_ENV: production

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: contacts-app-education-2024.tpcluster.de
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: helm-charts-frontend
                port:
                  number: 80
        # - path: /backend
        #   pathType: Prefix
        #   backend:
        #       service:
        #         name: helm-charts-backend
        #         port:
        #           number: 4000

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
