database:
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  env:
    NODE_ENV: development
    HOST: 0.0.0.0
    # PORT: "3000" # TODO define hier instead in deployment.yaml
    DB_HOST: helm-charts-database.default.svc.cluster.local
    # DB_PORT: "3306" # TODO define hier instead in deployment.yaml
    MARIADB_USER: test # TODO The name "root" is not possible, because it is already exist when the database is created
    MARIADB_PASSWORD: root
    MARIADB_DATABASE: contactsdatabase
    MARIADB_ROOT_PASSWORD: root
backend:
  image:
    repository: backend-local
    tag: latest
    pullPolicy: Never
  service:
    type: ClusterIP
    port: 3000
  env:
    NODE_ENV: development
    HOST: 0.0.0.0
    # PORT: "3000" # TODO define hier instead in deployment.yaml
    DB_HOST: helm-charts-database.default.svc.cluster.local # {{ .Release.Name }}-database
    # DB_PORT: "3306" # TODO define hier instead in deployment.yaml
    MARIADB_USER: test # TODO The name "root" is not possible, because it is already exist when the database is created
    MARIADB_PASSWORD: root
    MARIADB_DATABASE: contactsdatabase
    MARIADB_ROOT_PASSWORD: root
frontend:
  image:
    repository: frontend-local
    tag: latest
    pullPolicy: Never
  service:
    type: NodePort
    port: 80
  env:
    NODE_ENV: development

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: contacts-app-local
      paths:
        - path: /
          pathType: Prefix
          backend:
              service:
                name: helm-charts-frontend
                port:
                  number: 80
        # - path: /backend
        #   pathType: Prefix
        #   backend:
        #       service:
        #         name: helm-charts-backend
        #         port:
        #           number: 3000
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
