variables:
  IMAGE_NAME_BACKEND: crtpdev.azurecr.io/tsa/education/2024/contacts-backend
  IMAGE_NAME_FRONTEND: crtpdev.azurecr.io/tsa/education/2024/contacts-frontend

.docker_login: &docker_login
  - docker login crtpdev.azurecr.io -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

stages:
  - build

backend_build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - *docker_login
    - docker build -t ${IMAGE_NAME_BACKEND} -f ./Dockerfile .
    - docker push ${IMAGE_NAME_BACKEND}
    - docker rmi ${IMAGE_NAME_BACKEND}

frontend_build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG != null
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "dev"
  script:
    - *docker_login
    - docker build -t ${IMAGE_NAME_FRONTEND} -f ./frontend/Dockerfile ./frontend
    - docker push ${IMAGE_NAME_FRONTEND}
    - docker rmi ${IMAGE_NAME_FRONTEND}