apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000 # TODO define as a variable
      targetPort: 3000 # TODO define as a variable
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm-charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-backend
