apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
  selector:
{{ include "helm-charts.selectorLabelsBackend" . | indent 4 }}
