apiVersion: {{ .Chart.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-charts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}-database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-charts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-database
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "helm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-database
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.database.service.port }}
              protocol: TCP
					env:
						- name: NODE_ENV
              value: {{ .Values.database.env.NODE_ENV }}
						- name: HOST
              value: {{ .Values.database.env.HOST }}
						- name: PORT
              value: {{ .Values.database.env.PORT }}
						- name: DB_HOST
              value: {{ .Values.database.env.DB_HOST }}
						- name: DB_PORT
              value: {{ .Values.database.env.DB_PORT }}
						- name: MARIADB_USER
              value: {{ .Values.database.env.MARIADB_USER }}
						- name: MARIADB_PASSWORD
              value: {{ .Values.database.env.MARIADB_PASSWORD }}
						- name: MARIADB_DATABASE
              value: {{ .Values.database.env.MARIADB_DATABASE }}
						- name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.database.env.MARIADB_ROOT_PASSWORD }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
