apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.containerPort }}
      protocol: TCP
      name: http
  selector:
{{ include "helm-charts.selectorLabelsDatabase" . | indent 4 }}
