apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
{{ include "helm-charts.selectorLabelsBackend" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "helm-charts.selectorLabelsBackend" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "helm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
          - name: backend-port
            containerPort: {{ .Values.backend.service.port }}
            protocol: TCP
          env:
          - name: NODE_ENV
            value: {{ .Values.backend.env.NODE_ENV }}
          - name: HOST
            value: {{ .Values.backend.env.HOST }}
          - name: PORT
            value: "3000"
            # value: {{ .Values.backend.env.PORT }}
          - name: DB_HOST
            value: {{ .Values.backend.env.DB_HOST }}
          - name: DB_PORT
            value: "3306"
            # value: {{ .Values.backend.env.DB_PORT }}
          - name: MARIADB_USER
            value: {{ .Values.backend.env.MARIADB_USER }}
          - name: MARIADB_PASSWORD
            value: {{ .Values.backend.env.MARIADB_PASSWORD }}
          - name: MARIADB_DATABASE
            value: {{ .Values.backend.env.MARIADB_DATABASE }}
          - name: MARIADB_ROOT_PASSWORD
            value: {{ .Values.backend.env.MARIADB_ROOT_PASSWORD }}
          livenessProbe:
            initialDelaySeconds: 25
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.backend.service.port }}
          readinessProbe:
            initialDelaySeconds: 25
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.backend.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
