apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "helm-charts.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-frontend
