{{- if .Values.serviceAccount.create -}}
apiVersion: {{ .Chart.apiVersion }}
kind: ServiceAccount
metadata:
  name: {{ template "helm-charts.serviceAccountName" . }}
  labels:
{{ include "helm-charts.labels" . | indent 4 }}
{{- end -}}
